//! Generates the differential test cases into OUT_DIR/cases.rs.
//!
//! - BAREGEN_DIFFTEST_SEED  — u64 (decimal or 0x-hex) generator seed
//! - BAREGEN_DIFFTEST_CASES — number of coroutine bodies to generate

#[path = "build/ast.rs"]
mod ast;
#[path = "build/generator.rs"]
mod generator;
#[path = "build/render.rs"]
mod render;
#[path = "build/rng.rs"]
mod rng;

use std::env;
use std::fs;
use std::path::PathBuf;

const DEFAULT_SEED: u64 = 0xBA5E_BA11;
const DEFAULT_CASES: usize = 48;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=build");
    println!("cargo::rerun-if-env-changed=BAREGEN_DIFFTEST_SEED");
    println!("cargo::rerun-if-env-changed=BAREGEN_DIFFTEST_CASES");

    let seed = match env::var("BAREGEN_DIFFTEST_SEED") {
        Ok(s) => parse_seed(&s),
        Err(_) => DEFAULT_SEED,
    };
    let cases = match env::var("BAREGEN_DIFFTEST_CASES") {
        Ok(s) => s.parse().expect("BAREGEN_DIFFTEST_CASES must be a number"),
        Err(_) => DEFAULT_CASES,
    };

    let mut out = format!(
        "// Generated by baregen-difftest/build.rs — seed {seed:#x}, {cases} cases.\n\
         // Regenerate differently with BAREGEN_DIFFTEST_SEED / BAREGEN_DIFFTEST_CASES.\n"
    );
    // Cases are generated in order: a case may delegate (yield_all!)
    // only to earlier cases, so later generation needs the flavor and
    // worst-case yield bound of everything before it.
    let mut prior: Vec<generator::PriorCase> = Vec::new();
    for i in 0..cases {
        let case = generator::generate(seed, i, &prior);
        out.push_str(&render::render_case(i, &case));
        prior.push(generator::PriorCase {
            flavor: case.flavor,
            shape: case.shape,
            unit_yield: case.unit_yield,
            bound: case.bound,
        });
    }

    let path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("cases.rs");
    fs::write(path, out).unwrap();
}

fn parse_seed(s: &str) -> u64 {
    if let Some(hex) = s.strip_prefix("0x") {
        u64::from_str_radix(hex, 16).expect("bad hex BAREGEN_DIFFTEST_SEED")
    } else {
        s.parse().expect("bad BAREGEN_DIFFTEST_SEED")
    }
}
